---
- hosts: Logstash_server
  become: true
  tasks:  

#adding the Elasticsearch package as test to make sure Logstach will run
  - name: Adding Elasticsearch PGP Key
    shell: |
      wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
    args:
        warn: no

#Adding as well elastic serach repository for testing purposes
  - name: Adding Elasticsearch repository
    copy:
      dest: /etc/apt/sources.list.d/elastic-7.x.list
      content: |
        deb https://artifacts.elastic.co/packages/7.x/apt stable main

  - name: Installing OpenJDK Java
    apt:
      name: openjdk-11-jdk
      state: present

  - name: Transport Http for Logstash
    apt:
      name: transport http
      state: present


  - name: Installing jre
    apt:
      name: default-jre
      state: present

# Updtating and Installing the Logstash package 
  - name: Update logstash package
    apt:
      name: logstash
      state: present

  - name: Install logstash package
    apt:
      name: logstash
      state: present


# Enable and start the Elasticsearch service
  - name: Start logstash
    systemd:
      name: logstash
      state: started

  - name: Enable logstash
    systemd:
      name: logstash
      enabled: yes

