name: Ansible Actions

on: 
  push:
    branches:
      - "main"

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
          packages: write
          contents: read
          id-token: write

        steps:
          - run: echo "GitHub Actions Ansible"

          - name: Checkout
            uses: actions/checkout@v3

          - name: Install SSH Key
            uses: shimataro/ssh-key-action@v2
            with:
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              name: elk_keypair.pem
              known_hosts: unnecessary

          - name: AWS Authentication
            uses: aws-actions/configure-aws-credentials@v1
            with:
              role-to-assume: arn:aws:iam::254964228601:role/elk1-github-oidc
              aws-region: us-east-1
              role-session-name: GitHubActions

          - name: Perform ansible playbook to deploy
            uses: dawidd6/action-ansible-playbook@v2
            with:
              playbook: ./ansible/main-playbook.yml
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              options: |
                --inventory-file ./ansible/inventory.hosts